### ISSUE TITLE
A question from the beginner

### ISSUE THREAD

**Issue by Robin4-ever** [jtkim-kaist/VAD#38]
Hi,Kim,I'm just a new beginner,and i meet some problems when i run the code.
in the file "data_reader_DNN_v2",  in next_batch,  self._input_spec_list[self._num_file],  when i run it ,it reveals a IndexError : list index out of range.
i think that it is because there is no .txt file in VAD/sample_data
i don't know if this is true，hope for your answer.

**Comment by Robin4-ever** [comment]
I have solved this problem. it is a mistake made by myself…… 
anyway，thanks for the code.

**Comment by lxylxyoo** [comment]
Hi @Robin4-ever , I have met the same issue with you. Could you please tell me how you solved this problem ? Thanks!

**Comment by Robin4-ever** [comment]
Sorry,i have to say, it's been too long. i can't remember that. Maybe you can try it from two aspects:


1. the correct instruction. you must run the file as&nbsp;
run ./lib/python/VAD_test.py -m %d -l %d -d %d  --data_dir=./sample_data --model_dir=./saved_model --norm_dir=./norm_data'



2. check the path of the files. Find where the error occurred, maybe the path in the code doesn't have the file you want.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jtkim-kaist/VAD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午4:29
收件人:&nbsp;"jtkim-kaist/VAD"<VAD@noreply.github.com&gt;;
抄送:&nbsp;"xxxxxs"<1121172696@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jtkim-kaist/VAD] A question from the beginner (#38)





 
Hi @Robin4-ever , I have met the same issue with you. Could you please tell me how you solved this problem ? Thanks!

**Comment by lxylxyoo** [comment]
@Robin4-ever  Thanks for your quick reply!  I will have a try.
